### PR TITLE
移除 yaml 的安装依赖同时增加了对 clang-14 的支持

### PR DESCRIPTION
**Pull request by Guo-Shiyu**
1. 现在可以被 clang-14 编译了
2. 将 yaml-cpp 的依赖移动到 git submodule 中
3. 更新了 readme

### CODE REVIEW

**Comment by Guo-Shiyu** [comment]
clang-13 依然编译不过

**Comment by zavier-wong** [comment]
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:33 (target_compile_features):
  target_compile_features The compiler feature "cxx_std_20" is not known to
  CXX compiler

  "GNU"

  version 7.5.0.


-- Configuring incomplete, errors occurred!

好像编译不过

**Comment by Guo-Shiyu** [comment]
-- The CXX compiler identification is GNU 7.5.0 

当前使用的 c++ 编译器版本过低， 猜测是因为名称为 g++11  而非 g++

**Comment by zavier-wong** [comment]
我这边编译有问题，你好像把对g++的支持给去了。要不你换个环境，尽量能拉取后一次编译过

**Comment by zavier-wong** [comment]
项目已重构

**Pull request closed without merging**
